[[capitalization]]
== Species names

=== Capitalization and italics

Do not italicize common names. In the first reference, follow the common name with the scientific name italicized and in parentheses. 

- WRONG: The Golden-cheeked Warbler, _Dendroica chrysoparia_, is imperiled.
- RIGHT: The golden-cheeked warbler (_Dendroica chrysoparia_) is imperiled.

Do not capitalize common names of species except proper nouns and adjectives.

- Queen Anne’s lace, Canada thistle, spring beauty
- WRONG: The Bald Eagle sometimes preys on the American Pika.
- RIGHT: The bald eagle sometimes preys on the American pika.

NOTE: The convention among ornithologists is to capitalize both words in a standardized common »»name (based on the AOU Checklist). This is unique to ornithologists, and should only be used when the audience addressed is entirely ornithologists (i.e., a mix of herpetologists and ornithologists would indicate the noncapitalized usage).

Capitalize the genus in scientific names but not the species.

- _Aplodontia rufa_, _Draba cusickii_ var. _pedicellata_

Capitalize names for phylum, class, order, and family, but do not italicize.

- Chordata, Monocotyledoneae , Carnivora, Parulidae

Do not capitalize or italicize English derivatives of scientific names.

- amoeba, carnivore

=== Usage

It is appropriate for scientific organizations like GBIF to include the scientific names of species in our communications. This approach enhances clarity, as common names vary by region and across languages.

The scientific name of a species should immediately follow the first reference to the common name. Thereafter, a common name or shorter reference will suffice.

- The pallid bat (_Antrozous pallidus_) is found throughout most of the western United States. The bat has large ears, large eyes, a simple muzzle, and yellowish drab dorsal pelage.
