[[spelling]]
== Spelling and usage

=== Spelling

GBIF uses https://www.un.org/dgacm/en/content/editorial-manual/spelling[UN spelling^] as its default. In the absence of guidance from that source, we look to others (roughly in order of precedence):

* The Economist Style Guide, 12th edition (print only: no longer online 😔)
* http://www.theguardian.com/guardian-observer-style-guide-a[Guardian and Observer Style Guide^]
* http://handbook.reuters.com/index.php?title=A[Reuters Style Guide^]
* https://sites.google.com/a/ngs.org/ngs-style-manual/[National Geographic Style Manual^]

==== A

==== B

==== C

* COVID-19

==== D

==== E

==== F

==== G

==== H

==== I

==== J

==== K

==== L

==== M

==== N

==== O

==== P

==== Q

==== R

==== S

* SARS-CoV-2

==== T

==== U

==== V

==== W

==== X

==== Y

==== Z

=== Data

Uses of *datum* as singular and *data* as a collective plural are both acceptable; grammatically, both are treated as singular as in the sentence: "GBIF-mediated *data is* drawn from the holdings of more than two thousand institutions worldwide."

=== –ise vs. -ize.

This style (also favoured by the UN) is an accepted usage in British English, not simply an Americanization. Use of `–ize`, `-izing` and `-ization` is preferred, but not with `-yse`, e.g. analyse, catalyse.

=== Hyphenated words

Phrases connected by hyphens when they are collectively used as an adjective or modifier (phrasal adjective), as in this example:

> It is essential that scientists have access to fit-for-use data

BUT 

> These data are fit for use.

Some judgment calls remain, but note that we follow the https://www.un.org/dgacm/en/content/editorial-manual/spelling[UN style guide^] in using:

+ `policymaker` and `policymaking`
+ `decision maker`, `decision-making`

=== Quotation marks 

Double quotation marks used for direct quote from document, speech etc. Single quotes in all other cases.

Examples

> The Convention on Biological Diversity (CBD) defines biodiversity as “the variability among living organisms from all sources…this includes diversity within species, between species and of ecosystems.”

> The study looked at the quality of observations carried out by ‘citizen scientists’. 

=== Use of commas

Over-use: unnecessary after penultimate item in a list:

> The data fields include species name, location, date and time, and name of collector.

Under-use: commas can make meaning clearer by dividing sub-clauses 

> The manual, which has been published in order to facilitate sharing of biodiversity data, is aimed at information managers in natural history institutions.

=== Common problems to avoid

==== Passive voice

As a matter of style, passive voice is almost always inferior to active voice. With active voice, the subject acts; with passive voice, the subject is acted upon. It is important in telling our story that we take credit for the work we do—and not imply that it was done to us!

“For some reason, scientists notoriously use the passive voice—things are added, are measured, are found, and so on. Using the active voice forces you to be specific about who added, who measured, who found—and can point to holes in your story.”
—Cornelia Dean, Am I Making Myself Clear?: A Scientist’s Guide to Talking to the Public (2009)

WRONG: The matter will be given careful consideration.
RIGHT: We will give the matter careful consideration.
PREFERRED: We will consider the matter carefully.

==== The split infinitive	

WRONG: He was told to quickly process the data. 
RIGHT: He was told to process the data quickly. 

==== The dangling participle

WRONG: Straddling the Arizona–New Mexico border, the ecologist found a series of bat-dwelling caves. (Was the ecologist straddling the border?) 
RIGHT: The ecologist found a series of bat-dwelling caves straddling the Arizona–New Mexico border. (Better!)

==== Sexist language

`Avoid using he and she when referring to an unspecified person. Recast the sentence in the plural, or avoid the use of pronouns altogether. If you must refer to a single person, use he or she not he/she and never s/he.`

WRONG: chairman/chairperson, businessman, mankind
RIGHT: chair, business executive/business person, humankind

==== The longer of two similar words	

Long Word		Shorter/Better Form
facilitate		help
initialize		begin, start
necessitate		require
numerous		  many
utilize			  use
utility			  usefulness

